version: '2'
services:
  jhipsterprojetgestionpatient-app:
    image: jhipsterprojetgestionpatient
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterprojetgestionpatient-mysql:3306/jhipsterprojetgestionpatient?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://jhipsterprojetgestionpatient-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jhipsterprojetgestionpatient-elasticsearch:9200
    ports:
      - 8084:8084
  jhipsterprojetgestionpatient-mysql:
    extends:
      file: mysql.yml
      service: jhipsterprojetgestionpatient-mysql
  jhipsterprojetgestionpatient-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jhipsterprojetgestionpatient-elasticsearch
